blank_issues_enabled: false
contact_links:
  - name: Questions and Discussion
    url: https://github.com/sp-tarkov/bento/discussions
    about: Ask questions and discuss ideas in GitHub Discussions.
